defaults:
  - inference: generator     
  - ret_eval: ret_test
  - ret_finetune: ret_finetune  
  - _self_                 

datapath: ../data/
vector_store_path: "../vector_db"
chunk_size: 300
chunk_overlap: 15
dataset: ODQA
openai_key: ''
seed: 42

# Retrieval 설정
retrieval:
  top_k: 5
  model_name: "nlpai-lab/KoE5"
  rerank: True
  reranker_model_name: "BAAI/bge-reranker"

eval_data_path: "data/ephemeral/data/LabQ/selected_eval.csv"
retriever_type: "dense"
embedding_model_source: "huggingface"
embedding_model_name: "nlpai-lab/KoE5"
rarank: True
reranker_model_name: "BAAI/bge-reranker"
llm_model_source: "naver"
llm_model_name: "gpt-3.5-turbo"
chat_template: |
  주어진 문서를 바탕으로 질문에 답해주세요. 주어진 문서가 table일 경우 이를 해석해서 대답해주세요. 만약 주어진 문서에서 답을 찾을수 없는경우 답할 수 없다고 대답해주세요.
  {docs}
batch_size: 16
g_eval: True
mode: retrieve